### ISSUE TITLE
App breaks between 4.0.11 and 4.0.15 with Tried accessing nonexisting field (photos) on node type (URL)

### ISSUE THREAD

**Issue by egekhter** [facebook/facebook-php-sdk-v4#326]
The call that works in 4.0.11 and breaks in 4.0.15 is:

(new FacebookRequest(
                    $fbSession, 'GET', "/{$next_url}"
                ))->execute()->getGraphObject(GraphUser::className());

Stack trace:
[2015-01-22 18:17:42] local.ERROR: exception 'Facebook\FacebookAuthorizationException' with message '(#100) Tried accessing nonexisting field (photos) on node type (URL)' in /home/reflectera/vendor/facebook/php-sdk-v4/src/Facebook/FacebookRequestException.php:104
Stack trace:
#0 /home/reflectera/vendor/facebook/php-sdk-v4/src/Facebook/FacebookRequest.php(268): Facebook\FacebookRequestException::create('{"error":{"mess...', Object(stdClass), 400)
#1 /home/reflectera/app/models/processing/FacebookOrganize.php(55): Facebook\FacebookRequest->execute()
#2 /home/reflectera/app/models/processing/FacebookOrganize.php(63): get_all(Object(Facebook\FacebookSession), Object(Facebook\GraphAlbum), NULL)
#3 /home/reflectera/app/controllers/integration/FacebookController.php(202): FacebookOrganize::listAlbums(Object(Facebook\FacebookSession), '.....')

**Comment by SammyK** [comment]
This this throwing a `FacebookAuthorizationException` which is an error response from the Graph API, not the SDK.

Graph v2.2 support was added to SDK `v4.0.12` and there were a number of [changes in Graph 2.2](https://developers.facebook.com/docs/apps/changelog). I can't tell specifically what part of your request is not supported in Graph 2.2 since you didn't provide it in the post, but you'll need to change your request so that it is Graph 2.2 compliant. :)
