### ISSUE TITLE
Support video uploads to graph-video.facebook.com

### ISSUE THREAD

**Issue by gfosco** [facebook/facebook-php-sdk-v4#354]
To support resumable video uploads, there should be a method or automatic functionality to switch the Graph API URL to graph-video.facebook.com

The documentation for publishing video:  https://developers.facebook.com/docs/graph-api/reference/v2.2/page/videos#publish

Example patch done by a FB partner: https://github.com/zoharbabin/facebooktests/blob/master/src/Facebook/FacebookRequest.php#L221

@SammyK @yguedidi Comments on the method used in this patch / suggestions? (I'd like this to happen in both 4.0 and 4.1)

**Comment by SammyK** [comment]
This functionality was added to 4.1 in #279. You can see it supports both [video](https://github.com/facebook/facebook-php-sdk-v4/pull/279/files#diff-c05299fe394b8fb52b4a83a36cae6447R50) & [video-beta](https://github.com/facebook/facebook-php-sdk-v4/pull/279/files#diff-c05299fe394b8fb52b4a83a36cae6447R60) URL's.

In order to get this working in 4.0 it would require a major refactor since 4.0 has a broken implementation of form encoding. It always assumes `application/x-www-form-urlencoded` so properly encoding and sending files as `multipart/form-data` is not possible.

4.1 fully supports both encodings, but getting 4.0 to do the same would be a lot of work. :)

If someone wants to port over the 4.1 encoding changes to 4.0 in a non-breaking way, it's all theirs. :)

**Comment by yguedidi** [comment]
I don't' know if we really have to fix it in 4.0...

**Comment by YOzaz** [comment]
@SammyK I can actualy confirm that 4.0 it is sending files to Facebook without any problems, except it breaks for files over 100 Mb. Is that related to data encoding type as well?

**Comment by SammyK** [comment]
@YOzaz If you're using cURL or Guzzle, you probably won't have too much of an issue except for the timeout. It's the stream wrapper that's broken.
