### ISSUE TITLE
Q: How to log users out? getLogoutUrl()?

### ISSUE THREAD

**Issue by rvarbanov** [facebook/facebook-php-sdk-v4#385]
I use the JS SDK to log users to my site and to get `$accessToken`.
```
$jsHelper = $facebook->getJavaScriptHelper();
$accessToken = $jsHelper->getAccessToken();
```

How do I get `getLogoutUrl()` to work?

**Comment by SammyK** [comment]
This will log a user out of Facebook completely, not just your app. So unless you've got a specific edge case where you need to do this, it's usually not a common practice.

But the logout functionality within 4.1 of the PHP SDK is located in the `FacebookRedirectLoginHelper`. Not really the best place for it since as you pointed out if you're interfacing with the `FacebookJavaScriptHelper`, then it's weird to have to create an instance of  `FacebookRedirectLoginHelper` to log a user out. (Adding this to the 4.2 TODO list).

Anywho, this is how you log a user out with the PHP SDK v4.1:

```php
$fb = new Facebook\Facebook([/* */]);

$helper = $fb->getRedirectLoginHelper();

$logoutUrl = $helper->getLogoutUrl('{access-token}', 'http://example.com');
echo '<a href="' . $logoutUrl . '">Logout of Facebook!</a>';
```

Where `http://example.com` is the URL the user should be redirected to after logging out.

**Comment by gfosco** [comment]
Ok, we'll see this in 4.2 then.. :+1:
