### ISSUE TITLE
ORM like functions

### ISSUE THREAD

**Issue by devmsh** [facebook/facebook-php-sdk-v4#407]
Based on #406, I think this parts of the idea must be discussed separability, because it effect both the current `GraphObject` and the new suggested `OpenGraphObject` as well.

I suggest to develop the `GraphNodes` to have ORM like functionality and allow the user to delete or update some nodes directly using setter functions and `save` function that auto generate the required request. the same for `delete`. More advanced option is to have a relation function like `getLikes` or `addLike` and to offer eager or lazy-loading approach to get the data?

If the Idea is accepted in the `GraphObject` level, it will be used also in the new `OpenGraphObject` level to provide create new Actions like having `read` function in the `GraphObjectArticle` class and `scrape` or `update` function in the `OpenGraphObject` itself.

Quick example
$response = $fb->get('me');
$me = $response->GraphUser();
$me->setFirstName('My First Name');
$me->save();

$response = $fb->get('me/photos');
$photos = $response->GraphList('GraphPhoto')->asArray();
$photos[0]->delete();

**Comment by yguedidi** [comment]
I'm :-1: on this. It breaks SOLID principe, especially the Single Responsability Principe (SRP), it gives too much responsabilities to the `GraphObject`, which is by definition a Value Object.
BTW, thanks for your participation :)

**Comment by devmsh** [comment]
Thanks @yguedidi 

Did you have a problem with the idea of having ORM like feature? or you just need to divide such a functionality in a different classes? the `GraphObject` may have the setter and getter, while the entityManager contain the other suggested functionality?

**Comment by yguedidi** [comment]
I don't. But I don't like things that breaks SOLID, and the Active Record pattern you suggest breaks SOLID.
Why not something like Doctrine, ie Repository and Unit Of Work patterns?

**Comment by devmsh** [comment]
Yes, this is what I'm mention in the last comment, Doctrine use entityManager to solve the problem you mentioned before.

If I understand, you have a problem with the suggestion design and code sample not with the ORM idea itself?

**Comment by yguedidi** [comment]
Exactly! :)

**Comment by SammyK** [comment]
I think this is a really fantastic idea! But I'm not sure it should go into the official SDK. Since it really falls under the category of "cool API", I think you could go many different way on this one and it would require a lot of support to be properly maintained.

A "cool API" idea was the driving force behind my [Facebook Query Builder](https://github.com/SammyK/FacebookQueryBuilder) lib (which I'm rewriting). :) But the original approach I had ended up being a lot more work than I anticipated and I made it worse by making another one of my libs depend on it. :/

So I'd recommend you offer this as your own open source lib. I might even send a PR or two. :)

**Comment by yguedidi** [comment]
I agree ;)

**Comment by devmsh** [comment]
mmmm

Once we are finished from support all the standard types and Open Graph types, I will return back to this idea. It may be developed as a plugin to the Official SDK :)
