### ISSUE TITLE
type auto detection

### ISSUE THREAD

**Issue by devmsh** [facebook/facebook-php-sdk-v4#408]
One of my concerns while using the SDK, is why I need to specifically cast the response manually to specific node type?

We have both `type` field and `metadata=1` that they can help us dynamically detect the type of returned data even for single object like `/me` or for list response with multiple type like `/me/feed`.

in the first scenario `me?metadata=1` will return the `type` field inside the `metadata` object that specify that the response represent a user, so we did not need to use `getGraphUser`?

in the second scenario `/me/feed` response will contain the `type` field of each object, so we can convert each object to the corresponding `Graph{type}` if supported?

**Comment by yguedidi** [comment]
Just because in most cases you don't use metadata.

I think metadata are useful when you explore the Graph API with your code, but not when you know what you get. (e.g. when I request `/me`, as a developer, I know I can expect a user node, so I'll use `getGraphUser()`)

Moreover, they're too long, and in the context of API exchanges, you'll need the smallest response for a quicker response time.

**Comment by devmsh** [comment]
About metadata, Yes it will make the response too big.

In the other hand `me/feed` return the type of each story by default, so we can use this information whenever it available?

**Comment by yguedidi** [comment]
I think we shouldn't guess the return type at all.
In a "you know what you get" basis, the dev should ask for what he/she expect. And imagine, how you'll write the PHPDoc? :)

**Comment by SammyK** [comment]
I like the idea and I think it could be useful in some very specific cases where the Graph API returns multiple node types on the same edge/field (like the [owner field on the Event node](https://developers.facebook.com/docs/graph-api/reference/v2.3/event#readfields)).

But I wouldn't make it the default option for handling responses. Mainly because of what @yguedidi said:

> In a "you know what you get" basis, the dev should ask for what he/she expect.

But I'm also just not sure how useful that type of functionality would be. Even if we added a specific method `getAutoDetectNode()` on the `FacebookResponse` class that auto-detected the node type, your IDE wouldn't know which node it was going to return of myriad nodes. So you wouldn't get any of the IDE support. And in your script you'd need to add logic to detect which type was returned. It would be better from an educational perspective to refer to the docs and know which node was being returned from which endpoints and explicitly program your app that way.

But it's a neat idea! :)

**Comment by gfosco** [comment]
I agree with Sammy and Yassine... It's a neat idea, though.
