### ISSUE TITLE
Error 77 - error setting certificate verify locations

### ISSUE THREAD

**Issue by Maikell84** [facebook/facebook-php-sdk-v4#425]
Hello,

I am using the getSessionFromRedirect() Method, to get a Facebook User Session:

    try {
        $session = $helper->getSessionFromRedirect();
    } catch(FacebookRequestException $ex) {
        echo "Error".$ex->getCode()." - ".$ex->getMessage();
    } catch(\Exception $ex) {
        echo "Error".$ex->getCode()." - ".$ex->getMessage();
    }
		
When I am doing this in a normal php-environment (php 5.5.9, nginx) it works fine. But when I am using exactly this code in a __.phar-archive__, it gives me an exception:

    77 - error setting certificate verify locations: CAfile: phar:///var/www/....../Frameworks/vendor/facebook/php-sdk-v4/src/Facebook/HttpClients/certs/DigiCertHighAssuranceEVRootCA.pem CApath: /etc/ssl/certs

I think this is the same problem, that is explained [here](https://github.com/facebook/facebook-php-ads-sdk/issues/80). However the solution which is provided in this link does not work with the facebook-php-sdk-v4, because there is no function "setCaBundlePath()"

Best regards
Michael

**Comment by gfosco** [comment]
Can you update the location directly in `Facebook/HttpClients/FacebookCurlHttpClient.php` ?

**Comment by Maikell84** [comment]
Yes that works!

When I change the line:

    CURLOPT_CAINFO         => __DIR__ . '/certs/DigiCertHighAssuranceEVRootCA.pem',

to

    CURLOPT_CAINFO         => '/var/www/myproject/certs/DigiCertHighAssuranceEVRootCA.pem',

(which is a folder outsine the .phar), it works perfect.

**Comment by gfosco** [comment]
I would just change it on your own copy... First time anyone has requested PHAR support.  But, I'm guessing that 5.0 will support this anyway.  Check out the master branch for all the (significant) changes coming.

**Comment by Maikell84** [comment]
Thank You.

**Comment by tobiastom** [comment]
I have the same problem. Is there any ETA when 5.0 might be released? 

I'd like to contribute a patch to fix it in the meantime for the current version if you are interested.

**Comment by SammyK** [comment]
It's [out](https://developers.facebook.com/docs/reference/php/5.0.0). :)

**Comment by tobiastom** [comment]
@SammyK Ok, my fault. I'm sorry, I did not compare version numbers… stupid me. 

Still, I have the same problem. The `.pem` file is still stored inside the directory and when you create a phar bundle curl will not be able to read this file.

**Comment by SammyK** [comment]
Based on [this discussion](https://github.com/thephpleague/oauth2-client/issues/214), it seems relatively "safe" to rely on the default CA bundle. Verifying the peer with cert fingerprint hashes would be the most ideal way to go, but that's a whole other can of beans... might need to be addressed for v6.

At any rate, you can just delete the config line referencing the `DigiCertHighAssuranceEVRootCA.pem` and it should be all dandy. But I'd recommend using the Guzzle HTTP client implementation since it properly falls back to the system CA bundle.

**Comment by tobiastom** [comment]
The problem is that every client implementation (cURL, stream and guzzle) reference the same cert file. Switching the `http_client_handler` does not solve this issue. 

Secondly I cannot just delete the line. We have a continuous integration server running that fetches the composer packages and builds a deployable version. The only way I could do it would be to fork the Facebook SDK and fix it for myself.

**Comment by tobiastom** [comment]
Just for the record: I solved it with this subclass for now: https://gist.github.com/tobiastom/903bdb7d04c83b85cef6 and I set the option `http_client_header` to an new instance of this class. It's not nice, but it works.

**Comment by SammyK** [comment]
Glad you figured a workaround! A few days ago I posted a blog explaining how to [write a Guzzle 6 HTTP client implementation](https://www.sammyk.me/how-to-inject-your-own-http-client-in-the-facebook-php-sdk-v5#writing-a-guzzle-6-http-client-implementation-from-scratch) for v5 of the PHP SDK. A custom Guzzle 6 implementation might be a better option if you're already using composer for deployment. That way you don't have to worry about the CA bundle that comes with the PHP SDK since Guzzle will fall back to the server CA bundle.

At any rate this is certainly something that we'll need to address in v6. :)
