### ISSUE TITLE
[5.0] Guzzle v6 issue

### ISSUE THREAD

**Issue by serhatdurum** [facebook/facebook-php-sdk-v4#450]
Hello,

When we upgraded our guzzle version to latest(6.0.1) and when we are using `` 'http_client_handler' => 'guzzle' `` option, the code didn't work.

I will send a pull request but if you want to stay with current version, respect your toughts :smiley:

**Comment by SammyK** [comment]
This is something we should slate for v6 since it's a BC. :)

Until then you can just code a Guzzle 6 implementation of the HTTP client to the `FacebookHttpClientInterface` and inject it with the same `http_client_handler` option.

```php
class Guzzle6HttpClient implements FacebookHttpClientInterface {
    public function send($url, $method, $body, array $headers, $timeOut) {
        // Do Guzzle 6 stuff here
    }
}

$fb = new Facebook\Facebook([
    'http_client_handler' => new Guzzle6HttpClient,
]);
```

Also in your PR I see you upped the minimum PHP version to 5.5. That's something we should slate for v6 as well since [5.4 EOL is coming up in 3 months](http://php.net/supported-versions.php).

**Comment by serhatdurum** [comment]
@SammyK thanks :) 

yes minimum php version might be problem so , i closed my pr.Maybe next version ;)

**Comment by gfosco** [comment]
I would gladly accept a PR that provided a non-breaking addition to 5.0 with a Guzzle6HttpClient.

**Comment by serhatdurum** [comment]
@gfosco Guzzle 6 requires php: >=5.5.0 , so i closed my PR.If you think there will no problems with that , i can handle.

**Comment by SammyK** [comment]
Just wrote up a guide for [using the PHP SDK v5 with Guzzle 6](https://www.sammyk.me/how-to-inject-your-own-http-client-in-the-facebook-php-sdk-v5). Hope that helps! :)

**Comment by gfosco** [comment]
Awesome! :+1:
