### ISSUE TITLE
Need to support video upload in php sdk

### ISSUE THREAD

**Issue by codingtmd** [facebook/facebook-php-sdk-v4#453]
Hi Guys,

Facebook shipped a Resumable video upload api(https://developers.facebook.com/docs/graph-api/video-uploads) on F8, which will helps video publisher to achieve a more reliable uploading experience. In order to simplify the developer work, we want to add a helper class in php sdk, which will receive the single video file, cut it into small chunks and feed facebook chunked uploading api. 

We already add this functionality into Facebook python sdk(https://github.com/facebook/facebook-python-ads-sdk/blob/master/facebookads/video_uploader.py). And currently want to have the same thing in php sdk with our July release.

@YuanhuiChen  is working on this new sdk api right now. https://github.com/facebook/facebook-php-sdk-v4/pull/452

@SammyK just kindly noticed me that we didn't kick any discussion for this sdk api interface yet. I'm sorry. It is our mistake. But would like to start the discussion now and keep everyone in the same page.

Could you guys take a look at this diff and give us your insight feedbacks?

Thanks a lot,
Lei

**Comment by SammyK** [comment]
Hey @codingtmd!

> we want to add a helper class in php sdk, which will receive the single video file, cut it into small chunks and feed facebook chunked uploading api.

Cool - we should talk about API options. By default, video uploads should be non-resumable unless the developer explicitly starts a resumable session.

So this should go unchanged:

```php
$fb = new Facebook\Facebook([/* ... */]);

$data = [
  'title' => 'My Foo Video',
  'description' => 'This video is full of foo and bar action.',
  'source' => $fb->videoToUpload('/path/to/foo_bar.mp4'),
];

$response = $fb->post('/me/videos', $data, 'user-access-token');
```

Per [the docs](https://developers.facebook.com/docs/graph-api/video-uploads#resumable), resumable uploads have 3 phases:

1. Start
2. Transfer
3. Finish

As the PHP SDK strives to maintain a [ubiquitous language](http://martinfowler.com/bliki/UbiquitousLanguage.html) with the Facebook domain, the code should reflect the same nomenclature.

```php
$fb = new Facebook\Facebook([/* ... */]);

$data = [
  'title' => 'My Foo Video',
  'description' => 'This video is full of foo and bar action.',
  'source' => $fb->videoToUpload('/path/to/foo_bar.mp4'),
];

$client = $fb->getClient();

// This can throw an exception
// Returns `ResumableUpload` service
$resumable = $client->startResumableUpload('/me/videos', $data, 'user-access-token');

while ($resumable->bytesRemaining() > 0) {
    // This can throw an exception.
    // This will not move "next chunk" cursor until success response.
    // Can automatically retry sending chunk for any error response
    // returned that indicates the transfer can be tried again.
    $resumable->transferNextChunck($maxTries = 5);
}

if ($resumable->transferIsComplete()) {
    // This can throw an exception
    $res = $resumable->finish();
}
```

There are also a number of [resumable-upload-specific error responses](https://developers.facebook.com/docs/graph-api/video-uploads#errors) that the SDK might want to consider supporting with custom exceptions. Although I think we have too many as it is. :)

What do you guys think? cc: @yguedidi @gfosco 

> with our July release

What are you releasing in July? If the docs don't get updated on the dev site for v5 of the PHP SDK by July, then the product you're talking about releasing in July will still be based on the development version of the PHP SDK. Just something to consider. :)

**Comment by SammyK** [comment]
I'm starting to rethink the API a bit... I don't like how the `ResumableUpload` service class is mutable...

Since we rely on the Graph API to tell us which chunk size is next, we can't reliably predict the chunks in advance. So what if the transfer phase returns a `ResumableUploadCursor` which would contain the start & end bytes. Then you inject the cursor to get & transfer the next chunk. Then it's also up to the dev to handle max tries on failure, etc.

```php
$fb = new Facebook\Facebook([/* ... */]);

$data = [
  'title' => 'My Foo Video',
  'description' => 'This video is full of foo and bar action.',
  'source' => $fb->videoToUpload('/path/to/foo_bar.mp4'),
];

// This can throw an exception
// Returns `ResumableUpload` service
$resumable = $fb->startResumableUpload('/me/videos', $data, 'user-access-token');

$cursor = null;
while ($chunk = $resumable->getChunk($cursor)) {
    // If there was an unrecoverable error, the dev must fatal & exit
    $cursor = $resumable->transferChunk($chunk);
}

// This can throw an exception
$res = $resumable->finish();
```

Still not 100% amazing, but much better direction I think. This one's a though one. :)

**Comment by codingtmd** [comment]
That's great feedbacks!  Thanks very much, @SammyK !

I'm not sure whether we need to expose the resumable upload as public api in sdk now. The feedbacks we heard from our partners is, the existing resumable uploading are too complicate for them to implement, since most of them only want to upload video and they don't care it is resumable or non-resumable. They want us to provide an non-resumable simple public interface, but implement this public interface with real resumable uploading, so that they can get the benefits of our resumable uploading without any extra effort. This is the reason why we are currently trying to fill the gap in our php sdk. 

The interface we are asked to provided is like below:

$fb = new Facebook\Facebook([/* ... */]);

$data = [
  'title' => 'My Foo Video',
  'description' => 'This video is full of foo and bar action.',
  'source' => $fb->videoToUpload('/path/to/foo_bar.mp4'),
];

$client = $fb->getClient(); 
$response = $client->uploadVideo('/me/videos', $data, 'user-access-token');

User doesn't need to know how we use resumable upload inside uploadVideo.

Does it make sense to you?

with our July release
>>> it is my fault. I thought the php sdk has same release date as our H1 Graph API release(July 8). Never mind. I will update this information to our market team.

**Comment by codingtmd** [comment]
@SammyK , you post really fast:) and I like your suggestion about resumable uploading part too.

@YuanhuiChen, inside your uploadVideo function, could you implement the resumable uploading as @SammyK suggested?

public function uploadVideo($path, $data, $accessToken) {
     // This can throw an exception
     // Returns `ResumableUpload` service
     $resumable = $fb->startResumableUpload('/me/videos', $data, 'user-access-token');

     $cursor = null;
     while ($chunk = $resumable->getChunk($cursor)) {
         // If there was an unrecoverable error, the dev must fatal & exit
         $cursor = $resumable->transferChunk($chunk);
     }

     // This can throw an exception
     $res = $resumable->finish();
}

**Comment by codingtmd** [comment]
@SammyK , I just notice that I closed this issue accidentally. Sorry for that! Do you think we can make an agreement on API now? or we can schedule a meeting to accelerate the progress. @YuanhuiChen is currently blocked.

**Comment by SammyK** [comment]
@codingtmd I'd like to get feedback from @yguedidi on the API. But after [a conversation on the PHP Roundtable about this very issue](https://www.phproundtable.com/episode/psr-7-streams-immutability-middleware-oh-my), I'm starting to think we should abstract all this from the user and have an API that automatically chunks video uploads.

```php
$fb = new Facebook\Facebook([/* ... */]);

$data = [
  'title' => 'My Foo Video',
  'description' => 'This video is full of foo and bar action.',
  'source' => $fb->videoToUpload('/path/to/foo_bar.mp4'),
];

// Will automatically chunk out the video behind the scenes
$response = $fb->post('/me/videos', $data, 'user-access-token');
```

Lol. *Sigh.* Coding is hard.

**Comment by codingtmd** [comment]
@SammyK , agree! User doesn't need to know what happens inside the the api(chunked or non-chunked). In the $fb->post, we can trigger another code path to cut chunks and upload.

@yguedidi , could you comment?

**Comment by yguedidi** [comment]
Hi all!

@codingtmd @YuanhuiChen thanks for contributing.

So, my thoughts about the API: it should be simple, but not hidden.

As all the resumable logic need multiple Graph calls, I think our logic can't live in the `post()` function. `post()` means "one POST call to Graph API".

I suggest to add a `uploadVideo` helper method to `Facebook` with almost the same signature as the `FacebookVideoUploader->upload()` one, probably with one more bool argument for resumable or not. It will do all the logic about start, transfert and publish.
It will use a service class that expose 3 methods (something like `start(...)`, `transfer(...)`, `publish(...)`). This last service class can be used by users who want to perform their own logic (in case of batch requests for exemple)

**Comment by codingtmd** [comment]
@yguedidi, I feel happy with this. How about you, @SammyK ?

**Comment by yguedidi** [comment]
Quick night thoughts before I go to sleep:
- `ChunkNode` with `getStartOffset()`, `getLength()`, and a `isLast()` method
- `FirstChunckNode` that extends `ChunkNode` and add `getSessionId()` and `getVideoId()`
- `uploader->start($nodeId, $filePath, $accessToken, $isResumable)` returns a `FirstChunkNode`
- `uploader->transfer($sessionId, ChunkNode $chunk, $data)` return a `ChunkNode`
- `uploader->finish($sessionId, $params)` returns a boolean

Then, basicly, without error handling, the logic of `Facebook->upload(...)`:
```php
$chunk = $uploader->start('1234', $filePath, $accessToken, true);
$sessionId = $chunk->getSessionId();
$stream = fopen($filePath);

do {
    $data = stream_get_contents($stream, $chunk->getLength(), $chunk->getStartOffset())
    $chunk = $uploader->transfer($sessionId, $chunk, $data);
} while (!$chunk->isLast());

return $uploader->finish($sessionId, [/* endpoint parameters */]);
```

Thoughts?
We'll need to think about naming things, but now I can't, I'm tired.. :)

**Comment by SammyK** [comment]
> I suggest to add a uploadVideo helper method to Facebook

:+1: 

> `uploader->start($nodeId, $filePath, $accessToken, $isResumable)`

I'd kill `$isResumable` since the `start`, `transfer`, `finish` methods are inherently a part of the resumable upload process.

> `ChunkNode`

I'd just called it `StreamChunk` since it's not directly related to nodes and "stream" looks [a bit more PSR-7ish](https://github.com/php-fig/http-message/blob/master/src/StreamInterface.php). Either that or `TransferChuck` which would be more Facebook DSL.

> `FirstChunckNode`

I'd say either `FirstStreamChunk` or `FirstTransferChunk`.

Other than that - I'm really digging it! :)

Man - all this would be so much easier if we could just use [Guzzle](http://guzzle.readthedocs.org/en/latest/psr7.html#streams). *cough* @gfosco *cough*. :)

**Comment by yguedidi** [comment]
> I'd kill $isResumable since the start, transfer, finish methods are inherently a part of the resumable upload process.

:+1: It was too late in the night :)

I prefer `TransferChuck`/`FirstTransferChuck`

**Comment by SammyK** [comment]
> I prefer TransferChuck/FirstTransferChuck

:+1:

**Comment by codingtmd** [comment]
Great! Thanks, @yguedidi  and @SammyK . So let's briefly summary it.

- add TransferChunk with getStartOffset(), getLength(), and a isLast() method
- add FirstTransferChunk that extends TransferChunk and add getSessionId() and getVideoId()
- add a FacebookVideoUploader help class, which has following functions:
  - uploader->start($filePath, $accessToken) returns a FirstTransferChunk
  - uploader->transfer($sessionId, ChunkNode $chunk, $data) return a TransferChunk
  - uploader->finish($sessionId, $params) returns a boolean
  - uploader->upload($filePath, $accessToken), which will be implemented as below(with error handling)
```
$chunk = $uploader->start($filePath, $accessToken, true);

$sessionId = $chunk->getSessionId();
$stream = fopen($filePath);

do {
    $data = stream_get_contents($stream, $chunk->getLength(), $chunk->getStartOffset())
    $chunk = $uploader->transfer($sessionId, $chunk, $data);
} while (!$chunk->isLast());

return $uploader->finish($sessionId, [/* endpoint parameters */]);
```

And is there anything we need to notice for error-handling part?

**Comment by gfosco** [comment]
Glad you're all working well together on this (our community here rocks!).  I'll get the docs loaded in time, so that there's no discrepancy across the SDKs, though you're right we don't follow the Graph API release specifically.

There's a docs folder with dev-site style markup, where a page can be added for the new things like FacebookVideoUploader, anything that's public.

**Comment by SammyK** [comment]
Close! :)

> uploader->upload($filePath, $accessToken), which will be implemented as below(with error handling)

The `upload()` method will be added to the main `Facebook\Facebook` service and it will be a wrapper for the `start()`, `transfer()`, & `finish()` flow.

Also I'd call the method `resumableUpload()` to be more explicit about what it's doing behind the scenes.

> $stream = fopen($filePath);

The `FacebookFile` already opens a stream to the file and has a [getContents()](https://github.com/facebook/facebook-php-sdk-v4/blob/master/src/Facebook/FileUpload/FacebookFile.php#L94-L102) method. That would be updated to support `$length` & `$offset` with defaults to return the whole file.

Also need to add a `getSize()` method.

The dev experience would look like this:

```php
$fb = new Facebook\Facebook([ ]);

$data = [
  'title' => 'My Foo Video',
  'description' => 'This video is full of foo and bar action.',
];
$file = $fb->videoToUpload('/path/to/foo_bar.mp4');

// Will automatically chunk out the video behind the scenes
$response = $fb->resumableUpload('/me/videos', $file, $data, 'user-access-token');
```

Then the `resumableUpload()` would be doing all chunking:

```php
function resumableUpload($endpoint, FacebookFile $file, array $params = [], $accessToken = null, $graphVersion = null) {
    $uploader = $this->getResumableUploader($accessToken, $graphVersion);

    $chunk = $uploader->start($endpoint, $file->getSize());

    do {
        // would do the work of sending the proper file chunk based on $chunk
        $chunk = $uploader->transfer($endpoint, $chunk, $file);
    } while (!$chunk->isLast());

    return $uploader->finish($endpoint, $chunk->getUploadSessionId(), $params);
}
```

Does that sound right @yguedidi?

**Comment by yguedidi** [comment]
@SammyK almost right yes!

Now I remember why `$isResumable` haha: I want the helper dedicated to video upload, not only resumable ones.

And as endpoints for video upload have the same format, `/[node-id]/videos`, I'd prefer to only ask for that node id to the end-user.
The same goes for the video file, why force the user to give us a `FacebookFile` instance while we can just require the file path and create the instance in the helper? (I'm saying that only because we are in the context of a helper method)

So, something like `Facebook->videoUpload($nodeId, $filePath, $params, $isResumable, $accessToken)` would be OK for me :)

I don't have hard thought about the default value of `$isResumable`, but I think false might be good, has resumable video uploads is a recent feature.

**Comment by SammyK** [comment]
> Now I remember why `$isResumable` haha: I want the helper dedicated to video upload, not only resumable ones.

I think uploading via the `videoUpload()` method should always be chunked by default. Non-resumable downloads can be uploaded using the existing file-upload API. :)

> The same goes for the video file, why force the user to give us a FacebookFile instance while we can just require the file path and create the instance in the helper?

I agree. For the dedicated `videoUpload()` method, we can instantiate a `FacebookFile` instance for them.

```php
$fb = new Facebook\Facebook([ ]);

$data = [
  'title' => 'My Foo Video',
  'description' => 'This video is full of foo and bar action.',
];
$file = '/path/to/foo_bar.mp4';

// Will automatically chunk out the video behind the scenes
$response = $fb->videoUpload('/me/videos', $file, $data, 'user-access-token');
```

**Comment by yguedidi** [comment]
With our current throughts, the upload is not really **resumable**, it's "just" a chunked upload...

Solution:
- `uploadVideo()` which is mean just a video upload, chunked or not, that's why I suggest an argument `$isResumable`.
- `resumeUpload()` that get the exception thrown by `uploadVideo()` when it fail.

Use case:
I think that kind of upload will mostly used asynchronously (RabbitMQ, etc..), so a failed chunk upload can be retry later.
Chunks are useless if the SDK synchronously upload each of them in the current request...

**Comment by yguedidi** [comment]
not chunked upload, a.k.a. normal upload:
```php
$fb = new Facebook\Facebook([ ]);

$data = [
  'title' => 'My Foo Video',
  'description' => 'This video is full of foo and bar action.',
];
$file = '/path/to/foo_bar.mp4';

$response = $fb->uploadVideo('me', $file, $data, false, 'user-access-token');
```
chunked upload:
```php
$fb = new Facebook\Facebook([ ]);

$data = [
  'title' => 'My Foo Video',
  'description' => 'This video is full of foo and bar action.',
];
$file = '/path/to/foo_bar.mp4';

$response = $fb->uploadVideo('me', $file, $data, true, 'user-access-token');
```
chunked/resumable upload, a.k.a. async job
```php
$fb = new Facebook\Facebook([ ]);

try {
    // in case of a new upload
    // $nodeId, $data, $file, $accessToken come from the async message
    $response = $fb->uploadVideo($nodeId, $file, $data, true, $accessToken);

    // in case of a retry
    $response = $fb->resumeUpload($e);
} catch (UnfinishedUploadExceptionOrSomethingElse $e) {
    // send the async message to retry with the exception as data
}

// delete the file, it's uploaded to Facebook successfully
```

**Comment by SammyK** [comment]
Yeah, I agree, but we still don't need `$isResumable` though. That should be taken for granted when using the `uploadVideo()`. Otherwise we'd just be duplicating existing functionality by uploading a video with `post()`.

I really like the `resumeUpload()` idea. Maybe a `FacebookUploadChunkException` could be thrown for any transfer error that could be resumed. The dev could catch the error and resume the upload. That way it wouldn't be too hard to code a "retry with max attempts" kind of thing.

```php
try {
    $response = $fb->videoUpload('/me/videos', $file, $data, 'user-access-token');
} catch (FacebookUploadChunkException $e) {
    uploadRetryer($e);
}

function uploadRetryer(FacebookUploadChunkException $e, $attempt = 0) use ($fb) {
    if ($attempt > 5) {
        return false; // or whatever...
    }

    try {
        $fb->resumeUpload($e);
    } catch (FacebookUploadChunkException $e) {
        uploadRetryer($e, $attempt++);
    }
}
```

Or maybe the `uploadRetryer()` could be a method in the PHP SDK? :)

**Comment by yguedidi** [comment]
We should not decide for the user if the upload should be chunked or not. This decision should be in the hand of the user.
He/She would decide to chunk or not based on the file size, or maybe he/she don't want to make multiple server-side requests to the Graph API.

What if we rename `$isResumable` to `$useChunksOrSomethingElse`? Then we'll have 2 cases:
- `uploadVideo()` without chunks: a semantic shortcut for `post()`
- `uploadVideo()` with chunks: upload chunks until there is an exception, which is resumable with `resumeUpload()`

About including `uploadRetryer` in the SDK, I thought a new thing: rename `$isResumable` to `$retiesCountOrSomethingElse`!
Then:
- `uploadVideo(..., 0, ...)`: sync upload without retries, so it's exactly a `post()` shortcut, because when I explicitly don't want to retry, I don't need some chunk to be already uploaded :)
- `uploadVideo(..., 5, ...)`: sync upload with 5 retries using chunks, so it will work mostly like your `uploadRetryer()`, and there still are the exception and `resumeUpload()`

**Comment by codingtmd** [comment]
@yguedidi , we don't want user to make the decision. Existing non-chunked uploading brings us lots of trouble to either uploading/encoding for large file. So we don't want to encourage user to use non-chunked uploading any more. So we only want to receive chunked upload in the future and deprecate the non-chunked upload as much as we can. If user want to use non-chunked way, they should use this php sdk and let the sdk to cut the chunks for them. 

I agree with @SammyK  at this point. We probably should remove $isResumable from interface.

**Comment by SammyK** [comment]
> We should not decide for the user if the upload should be chunked or not. This decision should be in the hand of the user.

Sounds like according to @codingtmd Facebook wants chunking, so once we get the feature added, we'll need to update the docs to show examples using this new chunked method. :)

> About including uploadRetryer in the SDK, I thought a new thing: rename $isResumable to $retiesCountOrSomethingElse!

Yes! Love that idea. So the method signature could look like this:

```php
$response = $fb->videoUpload('/me/videos', $file, $data, 'user-access-token', $maxTries = 5);
```

**Comment by codingtmd** [comment]
OK. Let' summary again and split this task to steps:

# 1. add the chunked upload interface# 
The final interface should be
- add TransferChunk with getStartOffset(), getLength(), and a isLast() method
- add FirstTransferChunk that extends TransferChunk and add getSessionId() and getVideoId()
- add a FacebookVideoUploader help class, which has following functions:
 - uploader->start($filePath, $accessToken) returns a FirstTransferChunk
 - uploader->transfer($sessionId, ChunkNode $chunk, $data) return a TransferChunk
 - uploader->finish($sessionId, $params) returns a boolean
- Add a upload() method to the main Facebook\Facebook service and it will be a wrapper for the start(), transfer(), & finish() flow.
```
$fb = new Facebook\Facebook([ ]);

$data = [
  'title' => 'My Foo Video',
  'description' => 'This video is full of foo and bar action.',
];
$file = '/path/to/foo_bar.mp4';

$response = $fb->uploadVideo('me', $file, $data, 'user-access-token', $maxTries = 5);

function uploadVideo($endpoint, FacebookFile $file, array $params = [], $accessToken = null, $maxTries = 5) {
    $uploader = $this->getResumableUploader($accessToken);

    $chunk = $uploader->start($endpoint, $file->getSize());

    do {
        // would do the work of sending the proper file chunk based on $chunk
        $chunk = $uploader->transfer($endpoint, $chunk, $file);
    } while (!$chunk->isLast());

    return $uploader->finish($endpoint, $chunk->getUploadSessionId(), $params);
}
```

@SammyK  and @yguedidi , could we get agreement on this first? `If no one objects this, @YuanhuiChen will start coding on this part`

# 2. add uploadretry and resumable uplaod # 
I like the idea of uploadRetryer. It is beautiful, but not sure I understand its purpose.
- what does `$fb->resumeUpload($e);` in below code mean?  Retry an upload from beginning( like calling uploadvideo() again)? or pick up from where the uploading failed? if later, it might be over complicated since the uploader needs to track which stage it fails(start, transfer, or finish) and take different behavior for each case. I would more prefer to apply the $maxRetry into each stage(upload->start($maxRetry), upload->transfer($maxRetry), upload->finish($maxRetry)) to make the interface simple.

```
try {
    $response = $fb->videoUpload('/me/videos', $file, $data, 'user-access-token');
} catch (FacebookUploadChunkException $e) {
    uploadRetryer($e);
}

function uploadRetryer(FacebookUploadChunkException $e, $attempt = 0) use ($fb) {
    if ($attempt > 5) {
        return false; // or whatever...
    }

    try {
        $fb->resumeUpload($e);
    } catch (FacebookUploadChunkException $e) {
        uploadRetryer($e, $attempt++);
    }
}
```

Your thoughts?

**Comment by SammyK** [comment]
> function uploadVideo($endpoint, FacebookFile $file, array $params = [], $accessToken = null, $maxTries = 5) {

We don't want to typehint `FacebookFile` since it will be a string. We'll generate a `FacebookFile` for them based on the string they send in.

Other than that, I think that's pretty close to what we were talking about.

> what does $fb->resumeUpload($e); in below code mean?

It just sends a `FacebookUploadChunkException` to `resumeUpload`. 

The `FacebookUploadChunkException` is a special exception that will be thrown during the transfer phase only. And it will only be thrown when a resumable error is returned from Graph. It will have methods on it like `getFailedChunk()` that will provide the uploader with the necessary entities to retry the chunk upload.

> I would more prefer to apply the $maxRetry into each stage

The start and finish phases don't upload any chunked data an there inherently "not resumable" so they don't need a `$maxRetry`. See the [possible errors](https://developers.facebook.com/docs/graph-api/video-uploads#errors) that suggest "Retry upload." They are all in the transfer phase.

Excited to see the code for this! :)

**Comment by codingtmd** [comment]
@YuanhuiChen, we already have an agreement on the chunked upload interface. Hope this will unblock your work now.

@SammyK ,  one more question. Why we need uploadRetryer? will applying the $maxRetry in the transfer stage make the code simpler? I try to understand what the benefits are by introducing the uploadRetryer?

**Comment by SammyK** [comment]
> Why we need uploadRetryer?

I was just showing what it might look like for the "retry failing chunk uploads". It would only apply to the transfer phase. I can just add this functionality later if you guys want to focus on just getting the resumable uploader rocking. :)

**Comment by gfosco** [comment]
Closing, follow on in #489

**Comment by sardarsaab** [comment]
Is there any option to add call to action using php sdk in facebook page video?

**Comment by yguedidi** [comment]
Thank you for using the Facebook PHP SDK!

If you need help about using it, you should ask your questions on [StackOverflow](https://stackoverflow.com/) and tag them with the `facebook-php-sdk` tag.

So I'm closing this, but if you found a bug in the SDK or think about a feature, feel free to open a new GitHub issues.

**Comment by yguedidi** [comment]
@usamamashkoor please use StackOverflow for support questions. Thanks
