### ISSUE TITLE
Deep pagination appends original parameters

### ISSUE THREAD

**Issue by franmomu** [facebook/facebook-php-sdk-v4#483]
In `GraphEdge`, the method `getPaginationUrl` [appends the original parameters to the url for paginate](https://github.com/facebook/facebook-php-sdk-v4/blob/5.0-dev/src/Facebook/GraphNodes/GraphEdge.php#L181):

```php
// Pull in the original params
$originalUrl = $this->request->getUrl();
$pageUrl = FacebookUrlManipulator::mergeUrlParams($originalUrl, $pageUrl);
```

The problem here is that if you make, for example, this request:

`someone/feed?fields=id,message,created_time,likes&limit=15`

And then you want to iterate over the likes:

```php
$pagesEdge = $response->getGraphEdge();
// Only grab 5 pages
$maxPages = 5;
$pageCount = 0;

do {
  echo '<h1>Page #' . $pageCount . ':</h1>' . "\n\n";

  foreach ($pagesEdge as $page) {
    var_dump($page->asArray());

    $likes = $page['likes'];
    do {
      echo '<p>Likes:</p>' . "\n\n";
      var_dump($likes->asArray());
    } while ($likes = $fb->next($likes));
  }
  $pageCount++;
} while ($pageCount < $maxPages && $pagesEdge = $fb->next($pagesEdge));
```

You'll get this message: `FacebookResponseException in FacebookResponseException.php line 100:
(#100) Unknown fields: message,created_time.` because it appends the `fields` parameter to the pagination url.

I don't know if it is necessary to append the original parameters to the pagination.

**Comment by SammyK** [comment]
Good point! I don't have time to dig deeper into this right now, but I think there's some tweakage that will need to be done to the deep pagination. I'll try to take a look at this when I get some time maybe in about 2 weeks. Or maybe @yguedidi could figure it out. :)

**Comment by franmomu** [comment]
Ok, thanks! I've been reading [the documentation about paging](https://developers.facebook.com/docs/graph-api/using-graph-api/v2.4#paging) and, apparently, it looks like it will work with just this:

```php
public function getPaginationUrl($direction)
{
    $this->validateForPagination();

    // Do we have a paging URL?
    if (!isset($this->metaData['paging'][$direction])) {
        return null;
    }

    $pageUrl = $this->metaData['paging'][$direction];

    return FacebookUrlManipulator::baseGraphUrlEndpoint($pageUrl);
}
```

It works with my code (in the example, the outer pagination is time-based and the inner one is cursor-based), but I guess I'm missing something.

**Comment by gfosco** [comment]
@franmomu If you'd like to submit a PR for this, that'd be great.  Thanks

**Comment by SammyK** [comment]
Finally got around to looking at this in more detail. :)

@franmomu The original code is supposed to create next & prev URL's based on the cursor and parent node ID. This is because the Graph API doesn't always return the full pagination URL so it had to be created based on the returned cursors. But [the docs state](https://developers.facebook.com/docs/graph-api/using-graph-api/v2.4#paging):

> `next`: The Graph API endpoint that will return the next page of data. **If not included, this is the last page of data.**

And also:

> `previous`: The Graph API endpoint that will return the previous page of data. **If not included, this is the first page of data.**

So I guess I should have read that more carefully before adding all the auto-URL-generation functionality. Lol.

There are a number of features of the `GraphEdge` & `GraphNode` auto-casting that should be removed as well. But since they might be BC's, we should probably just leave them in for now and remove them in v6.0.

> in my code, the outer pagination is time-based and the inner one is cursor-based

Different endpoints in the Graph API support different types of pagination. In another query, the outer pagination could be cursor based and endpoints in the inner endpoints could be time-based or even offset-based. It just depends on the endpoints.

@gfosco This should be :+1: for merge so you can delete the `5.0-dev` branch. :)

**Comment by franmomu** [comment]
Thanks for merging! :) What I meant by the outer and inner pagination was that it worked with different endpoints.
