### ISSUE TITLE
MediaTemple: Fatal Error where DateTime() is being called

### ISSUE THREAD

**Issue by robbiegod** [facebook/facebook-php-sdk-v4#485]
I recently migrated from a cloud site on Rackspace to a DV server on MediaTemple for one of my websites.  I am using the Facebook PHP SDK v5.  When i was testing my application, I ran into some problems where I couldn't retrieve photos like i could on the other website.  It turned out that a fatal error was being thrown in one of my files.  The reason is that in the Facebook PHP SDK and also on my server, I wasn't setting the timezone.

Under PHP Settings in the Additional Directives box, I added this line: 
date.timezone = "America/New_York"

That fixed everything for me, but i am wondering if the timezone should be set within the Facebook PHP SDK to make it more portable and compatible with Media Temple.

**Comment by SammyK** [comment]
Thanks for sharing the info!

> i am wondering if the timezone should be set within the Facebook PHP SDK to make it more portable and compatible with Media Temple.

This isn't a Media-Temple-specific issue, but is related to any PHP environment that doesn't have the default timezone set in the php.ini. We don't want to have the PHP SDK set the time zone since that should be server & app-specific. If the PHP SDK set the timezone it would overwrite environments that are properly configured.
