### ISSUE TITLE
Tagging 5.1

### ISSUE THREAD

**Issue by gfosco** [facebook/facebook-php-sdk-v4#504]
So, now that @SammyK landed the video uploading, I'd like to tag a 5.1 release.

But, I want to ask you all if we've kept master clean for a 5.1 release or if we've already merged in 6.0 specific changes.  I haven't been too involved.  cc @yguedidi 

Let me know your thoughts on how we'll handle the 5.0-dev branch and the master branch going forward with a 5.1 release.

Thanks!

**Comment by SammyK** [comment]
I think @yguedidi has more experience with this than I do. I was thinking of putting all 5.x features into one branch (instead of a branch for every minor release). Then 5.x features get submitted to the 5.x branch and merged into master which will be 6.0.0-dev.

Does that sound about right?

**Comment by yguedidi** [comment]
Sorry for the delay, I don't have too much time.. @SammyK you almost right ;)

For now, we don't have any breaking change, and we don't plan anything for 6.0, so `master` is 5.x (see `composer.json` haha).

So my suggestions:
- merge `5.0-dev` in `master` (to have 5.0 bugfixes in 5.1, and to keep all commit hashes)
- make master the default branch
- remove `5.0-dev` branch
- tag a `5.1.0` release on the merge commit

As @SammyK says, we don't need a branch for every minor version because we follow SemVer now, and because we tell user to install the SDK with `~5.0`

The need for a `5.x` branch will come when we'll start working on 6.0.

**Comment by SammyK** [comment]
:+1:

**Comment by gfosco** [comment]
Excellent plan, that does sound perfect.  Opened #506

**Comment by gfosco** [comment]
Ok, merged and tagged 5.1.0!  I can't delete 5.0-dev because of the 1 open PR.  Also, is it possible that people have explicitly used the branch name in a project that will fail if I delete the branch?

**Comment by SammyK** [comment]
W00t! Don't know 100% about branch deleting ... that's a @yguedidi question. :)

**Comment by yguedidi** [comment]
@gfosco now you can delete it as the PR is merged.

I'm not sure people require `"facebook/php-sdk-v4": "dev-5.0-dev"` in their `composer.json`...
In that case, it will fail only on `composer update` because the branch doesn't exist anymore, but it will work on `composer install` thanks to `composer.lock` and the fact that we keep the last commit of that branch in `master`.

**Comment by gfosco** [comment]
I can't delete it yet because #496 is pointing to it. cc @SammyK
