### ISSUE TITLE
Event "place" -> not returned from API (works in API explorer)

### ISSUE THREAD

**Issue by HarryWiles** [facebook/facebook-php-sdk-v4#549]
API Explorer get the place data:
https://developers.facebook.com/tools/explorer/?method=GET&path=1670970116486035%3Ffields%3Did%2Cname%2Cstart_time%2Ccover%2Cplace&version=v2.5

PHP SDK get's everything except place:
- $response = $this->get_response("/{$fb_event_id}?fields=id,name,start_time,cover,place");
- ![image](https://cloud.githubusercontent.com/assets/203961/12579284/c7249de8-c41e-11e5-9619-05c3725204c6.png)

Any ideas?

**Comment by SammyK** [comment]
Hey @HarryWiles!

1. You just posted your app secret to the world so please go into your app settings an reset it.
2. You're dumping the `FacebookResponse` which represents the HTTP response, but you need to obtain the `GraphNode` which is a collection that contains the response data. Since this is an Event node you can do the following to obtain a `GraphEvent`:

```php
$eventNode = $response->getGraphEvent();
$place = $eventNode->getPlace();
```

**Comment by HarryWiles** [comment]
Thanks Sammy, I wasn't aware of the getPlace() method.
Very kind of you.
