### ISSUE TITLE
Type of thrownException ?

### ISSUE THREAD

**Issue by tolbon** [facebook/facebook-php-sdk-v4#585]
Hi people, 
I use phpstorm and php 7.0

I use this code find on :
[https://developers.facebook.com/](https://developers.facebook.com/docs/php/howto/example_batch_request?locale=en_US#multiple-user-example)

PHPstorm says $e->getResponse() not exist.
If i read the sdk. thrownException in FacebookResponse.php is type of FacebookSDKException and not  FacebookResponseException.

So my question is : Do I need cast $e on FacebookResponseException (so facebook example is wrong) or thrownException in sdk is not in a right type ?

Ps : the only way thrownException is set, is by FacebookResponseException::create

Thx for reading and your responses

**Comment by SammyK** [comment]
Hey @tolbon!

PhpStorm is not recognizing the method because the docblock for the `getThrownException()` method [says it returns a `FacebookSDKException`](https://github.com/facebook/facebook-php-sdk-v4/blob/master/src/Facebook/FacebookResponse.php#L216) when it actually returns a `FacebookResponseException`. 

Anyone want to make a PR to fix this this low hanging fruit? :)

**Comment by tolbon** [comment]
Thx @SammyK 

I do a PR for this.

Do I close this "issue" ?

**Comment by SammyK** [comment]
Sweet - thanks! Once you sign the CLA, I'll merge and we'll close all the things. :)

**Comment by SammyK** [comment]
Fixed in #586
